const List<String> googleFontNames = [
  'Roboto',
  'Lato',
  'Oswald',
  'Montserrat',
  'Open Sans',
  'Poppins',
  'Raleway',
  'Nunito',
  'PT Sans',
  'Merriweather',
  'Playfair Display',
  'Bebas Neue',
  'Rubik',
  'Work Sans',
  'Fira Sans',
  'Cabin',
  'Manrope',
  'Ubuntu',
  'Varela Round',
  'Kanit',
  'Teko',
  'Inter',
  'Arvo',
  'Exo 2',
  'Josefin Sans',
  'Dosis',
  'Anton',
  'Quicksand',
  'Mukta',
  'Assistant',
  'Pacifico',
  'Caveat',
  'Indie Flower',
  'Dancing Script',
  'Shadows Into Light',
  'Inconsolata',
  'DM Sans',
  'Noto Sans',
  'Source Sans 3',
  'Titillium Web',
  'Vollkorn',
  'Libre Baskerville',
  'Lora'
];
