name: Contributors
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  contributors:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || 
      github.event_name == 'schedule' || 
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: All Contributors Auto Action
        uses: JoshuaKGoldberg/all-contributors-auto-action@v0.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on recent activity
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Contributors workflow completed successfully');
