name: Contributors
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && 
       github.event.pull_request.merged == true && 
       github.event.pull_request.user.login != 'github-actions[bot]') || 
      github.event_name == 'schedule' || 
      github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
